"""empty message

Revision ID: 3d2a173bf8b7
Revises: 5a10c780a4fc
Create Date: 2021-01-12 09:53:48.698213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2a173bf8b7'
down_revision = '5a10c780a4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_hidden')
    # ### end Alembic commands ###
